<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FVEFBQR" failures="1" tests="11" name="TestCases.TextBoxTesting" time="223.850" errors="0" timestamp="09 Sep 2021 12:48:08 GMT" skipped="0">
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="24.629"/>
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="19.794"/>
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="19.066"/>
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="16.969"/>
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="20.110"/>
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="18.724"/>
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="18.690">
    <failure message=" expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at TestCases.TextBoxTesting.calendar(TextBoxTesting.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- calendar -->
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="19.964"/>
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="20.895"/>
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="19.906"/>
  <testcase classname="TestCases.TextBoxTesting" name="calendar" time="25.103"/>
</testsuite> <!-- TestCases.TextBoxTesting -->
